myapp/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.MyAppIndex, name='MyAppIndex')
]

newsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^myapp/', include('myapp.urls', namespace='myapp')),
    url(r'^admin/', admin.site.urls),
]

myapp/models.py
from django.db import models


class MessageBord(models.Model):
    new_message = models.TextField(null=False)

myapp/views.py
from django.shortcuts import render, redirect
from .models import MessageBord


def MyAppIndex(request):
    msg = request.GET.get('words')

    delete_text = request.POST.getlist('delete_text')
    if delete_text:
        MessageBord.objects.filter(id__in=delete_text).delete()

    data_list = MessageBord.objects.order_by('-id')
    contexts = {
        'result_list': data_list
    }

    if msg is not None:
        message_data = MessageBord()
        message_data.new_message = msg
        message_data.save()

    return render(request, 'myapp/index.html', contexts)

myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'myapp/css/style.css' %}">
    <title>Title</title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block body %}
<form action="{% url 'myapp:MyAppIndex' %}" method="get">
    <label>message : <input type="text" size="20" name="words" /></label>
    <input type="submit" value="send" />
</form>

    <form action="{% url 'myapp:MyAppIndex' %}" method="post">
        {% csrf_token %}
        {% include "myapp/result.html" %}
        <input type="submit" value="delete"/>
    </form>

{% endblock %}

myapp/templates/myapp/result.html
{% if result_list %}
{% for i in result_list %}
<p>{{ i.new_message }}</p>
{% endfor %}
{% endif %}